version: '3.8'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - prometheus_etc:/etc/prometheus/
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - monitor
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=test1234
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - prometheus
    networks:
      - monitor
    restart: always
volumes:
  prometheus:
  prometheus_etc:
  grafana:
  grafana_provisioning: