version: '3.1'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: elasticsearch
      MYSQL_ROOT_PASSWORD: elasticsearch
      MYSQL_USER: elasticsearch
      MYSQL_PASSWORD: elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.4
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
    volumes:
      - elasticsearchvolume
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Seoul
    user: root
    restart: always
    privileged: true
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.0
    ports:
      - 5601:5601
    networks:
      - default
    environment:
      ELASTICSERCH_UTL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      TZ: Asia/Seoul
    restart: always
    privileged: true
networks:
  elastic: